/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Dia6;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
       Scanner leitor = new Scanner(System.in);
       
        System.out.println("Digite a variável A: ");
        String variavelA = leitor.nextLine();
        
        System.out.println("Digite a variável B: ");
        String variavelB = leitor.nextLine();
        
        variavelA = variavelB;
        variavelB = variavelA;
        
        System.out.println("Variável A = " + variavelA);
        
        System.out.println("Variável B = " + variavelB);
    }
}
